### ISSUE TITLE
Remove keycode_ from the names of members of KeyCode and use snake case

### ISSUE THREAD

**Issue by Keithcat1** [chrisnorman7/dart_sdl#4]
Typing KeyCode.keycode_CAPSLOCK feels repetitive to me, since I'm already using the enums name to access the member. Also, I believe the naming convension for Dart is snake case, not underscore case? Since these are not raw bindings of SDL and users might get confused when they write code that assumes that KeyCode.capslock exists, please change it. Shouldn't be too hard since you have code generation? Maybe someone should go ask FFIGEN to add support for generating Dart-style enums and methods to convert between Dart and C-style enums like you're doing with your own code generation.

**Comment by chrisnorman7** [comment]
Hi @Keithcat1,
So snake case is using an underscore. I think you mean [camel case](https://en.wikipedia.org/wiki/Camel_case), and yes, that is what Dart recommends. I just left the snakes there for easier conversion (I think).

Secondly, if I were to remove the `keycode_` from the start of each member, any code that relies on it would need to be changed. I suspect that's mostly my code, but I've no desire to adopt such a fundamental breaking change without a better reason to do so than repetition. For what it's worth, in VS Code, I just type the actual key name, and autocomplete suggests the right member anyway.

I'm also not sure how it would look visually with members like `RETURN`. I have just tested, and it seems Dart won't complain about the use of a reserved keyword if it's in all caps, but it might look stranger than leaving the prefix.

If this were Python, I could get a list of reserved keywords programmatically, and append an underscore (`RETURN_`, for example) to any of them, but Dart doesn't provide such a thing as far as I know.

I'm not going to close this for now, because I actually think you raise a valid point about it being a bit daft to include the name of the enumeration, and have `KEYCODE_` at the start of the member too, but I'd like a bit more justification that minor inconvenience.

**Comment by chrisnorman7** [comment]
So as a bit of background on why I did such a U-turn:

- I had it in my head I'd already gotten the version number past 1.0.0, and as such the API should be considered stable.
- I didn't realise how easy it would be to change the code generator.
- I didn't realise how nice the resulting code would look!
On the flip side, anyone coming to these bindings from other languages may be a little upset that I've prefixed numerical codes with the word `digit`. I did that because that's what [Flutter](https://flutter.dev/) does with their [LogicalKeyboardKey](https://api.flutter.dev/flutter/services/LogicalKeyboardKey-class.html) class.
