### ISSUE TITLE
Use Set instead of List for things like KeyMods

### ISSUE THREAD

**Issue by Keithcat1** [chrisnorman7/dart_sdl#5]
The way that KeyMods works is best described by a set, not a list. Also sets are probably more efficient. What we could also do is to create:
```dart
class _KeyModFlags implements Set<KeyMod> {
  final int _modMask; // contains the keymod modifier mask we got from SDL
  const _KeyModFlags(this._modMask);
  bool contains(KeyMod value) {
    final cvalue = value.toSdlValue();
    return _keyMod & cvalue == 1;
  }
}
```
This can then be returned from any function with return type Set<KeyMod> and would be the most efficient of all, because it doesn't have to allocate one object per modifier key that was pressed and store it in a list.

**Comment by chrisnorman7** [comment]
Hi @Keithcat1,
I've implemented the set. I'm actually not sure another class would be much faster because enum members are constants anyways. I think more magic would just be error prone.

Happy to be proved wrong though. Unfortunately, I never bothered writing tests for the bindings, otherwise I could have actually given your suggestion the stress-testing it deserves.
